language: ruby
rvm:
  - 2.1
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html --file-ignore ./_site/bower_components/swagger-ui/dist/index.html,./_site/bower_components/swagger-ui/src/main/html/index.html,./_site/bower_components/swagger-ui/dist/o2c.html,./_site/bower_components/swagger-ui/src/main/html/o2c.html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
