language: ruby
rvm:
  - 2.4
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html --verbose true --ignore-script-embeds --file-ignore ./_site/bower_components/swagger-ui/dist/index.html,./_site/bower_components/swagger-ui/src/main/html/index.html,./_site/bower_components/swagger-ui/dist/o2c.html,./_site/bower_components/swagger-ui/src/main/html/o2c.html,./_site/bower_components/lunr.js/index.html,./_site/bower_components/lunr.js/test/index.html,./_site/bower_components/lunr.js/example/index.html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
