# Site settings
title: CoScale Support
email: support@coscale.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.coscale.com" # the base hostname & protocol for your site
twitter_username: coscale
github_username:  coscale
baseurl: /

# Build settings
markdown: kramdown

# Style
sass:
    sass_dir: bower_components/
    style: compress

# Exclude config files
exclude:
    - bower.json

# Collections
collections:
    docs_getting_started:
        output: true
        permalink: /getting-started/:name:output_ext
    docs_installation:
        output: true
        permalink: /installation/:name:output_ext
    docs_usage:
        output: true
        permalink: /usage/:name:output_ext
    docs_use_cases:
        output: true
        permalink: /use-cases/:name:output_ext
    docs_advanced:
        output: true
        permalink: /advanced/:name:output_ext


# Extra plugins
gems:
#     - 'jekyll-lunr-js-search'
    - jekyll-sitemap
