# Site settings
title: CoScale Support
email: support@coscale.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.coscale.com" # the base hostname & protocol for your site
twitter_username: coscale
github_username:  coscale

# Build settings
markdown: kramdown

# Style
sass:
    sass_dir: bower_components/
    style: compress

# Exclude config files
exclude:
    - bower.json
    - vendor
    - Gemfile
    - run-local.sh

# Collections
collections:
    docs_agent:
        output: true
        permalink: /agent/:path/
    docs_rum:
        output: true
        permalink: /rum/:path/
    docs_custom_metrics:
        output: true
        permalink: /custom-metrics/:path/
    docs_events:
        output: true
        permalink: /events/:path/
    docs_other:
        output: true
        permalink: /other/:path/
    docs_tools:
        output: true
        permalink: /tools/:path/
    docs_advanced:
        output: true
        permalink: /advanced/:path/
    docs_alerting:
        output: true
        permalink: /alerting/:path/
    docs_dashboard:
        output: true
        permalink: /dashboard/:path/
    docs_tutorials:
        output: true
        permalink: /tutorials/:path/

# Used for breadcrumbs, do not remove
breadcrumb_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

# Extra plugins
gems:
#     - 'jekyll-lunr-js-search'
    - jekyll-sitemap
