// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 3
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){




var Ca=this,Da=function(){var a=YT.Player,b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},Ea=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Fa=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Ga=function(a){if(null==a)return String(a);var b=Fa.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ha=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},la=function(a){if(!a||"object"!=Ga(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ha(a,"constructor")&&!Ha(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ha(a,b)},Ia=function(a,b){var c=b||("array"==Ga(a)?[]:{}),d;for(d in a)if(Ha(a,d)){var e=a[d];"array"==Ga(e)?("array"!=Ga(c[d])&&(c[d]=[]),c[d]=Ia(e,c[d])):la(e)?(la(c[d])||(c[d]={}),c[d]=Ia(e,c[d])):c[d]=e}return c};var pa=null,Ka=Math.random(),La=null,Ma=null,ya=!1,Na={},Oa={},za={};var Pa,Qa,Ra,Sa,Ta,Ua,Va,Wa,Ya,Za,$a,ab,bb,cb,db,eb,fb,gb,hb,ib,jb,kb,lb,mb,nb,pb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Mb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,S,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,qd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,
ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze,$e;
(function(){var a=function(a){return{toString:function(){return a}}};Pa=a("");Qa=a("0");Ra="";Sa=a("");Ta=a("");Ua=a("");Va=a("");Wa=a("");Ya=a("");Za=a("");$a=a("");ab=a("2");bb=a("3");cb=a("");db=a("");eb=a("");
fb=a("");gb=a("");hb=a("");ib=a("");jb=a("");kb=a("");lb=a("");mb=a("");nb=a("");pb=a("");rb=a("");sb=a("");tb=a("");ub=a("");
vb=a("");wb=a("");xb=a("");yb=a("");zb=a("");Ab=a("");Bb=a("");Cb=a("4");Db=a("");Eb=a("");Fb=a("");Gb=a("");Hb=a("");Ib=a("");Jb=a("");Kb=a("");Mb=a("");Ob=a("");
Pb=a("");Qb=a("");Rb=a("");Sb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("5");Yb=a("");Zb=a("");$b=a("6");ac=a("");bc=a("");cc=a("");dc=a("");ec=a("");
fc=a("");gc=a("");hc=a("");ic=a("7");jc=a("");kc=a("8");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");rc=a("");sc=a("9");tc=a("");uc=a("");
vc=a("");xc=a("");yc=a("");zc=a("");Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("10");Ic=a("");Jc=a("18");Kc=a("19");Lc=a("");Mc=a("");
Nc=a("11");S=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("12");Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");$c=a("");ad=a("");bd=a("");cd=a("13");dd=a("");ed=a("");
fd=a("");gd=a("");hd=a("");id=a("");jd=a("");kd=a("");ld=a("");md=a("");nd=a("");qd=a("");td=a("");ud=a("");vd=a("");wd=a("");xd=a("");yd=a("15");zd=a("");Ad=a("");Bd=a("");Cd=a("");
Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");
Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");ke=a("");
le=a("16");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");
Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je="";Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("17");Qe=a("");Re=a("");Se=a("");
Te=a("");Ue=a("");Ve=a("");We=a("");Xe=a("");Ye=a("");Ze=a("");$e=a("")})();var af=function(){},P=function(a){return"function"==typeof a},bf=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},cf=function(a){return"number"==Ga(a)&&!isNaN(a)},df=function(a){return/^[0-9]+$/.test(a)},ef=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},ff=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},Q=function(a){return Math.round(Number(a))||0},ha=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},gf=function(a){var b=[];if(bf(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},I=function(){return new Date},hf=function(a,b){if(!cf(a)||!cf(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},jf=function(){this.prefix="gtm.";this.values={}};jf.prototype.set=function(a,b){this.values[this.prefix+a]=b};jf.prototype.get=function(a){return this.values[this.prefix+a]};jf.prototype.contains=function(a){return void 0!==this.get(a)};
var kf=function(a,b,c){try{if(!a[hd])return a[Hc](a,b||af,c||af);c&&c()}catch(d){}return!1},lf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=ff(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},mf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},nf=function(a){return function(){return a("GTM-WJLV88")}},of=function(a){for(var b=0;b<a.length;b++)a[b]()},pf=I().getTime(),ka=function(){return"gtm"+
pf++},ma=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},qf=function(a,b,c){a.prototype["gtm_proxy_"+b]=a.prototype[b];a.prototype[b]=c},rf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},sf=function(a,b){0==b?a.Ta=!0:a.complete=!0;var c=a.g;a.s&&(a.s.Fa[c]=b);Na[c]&&(Na[c].state=b)},tf=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var E=window,K=document,wf=navigator,O=function(a,b,c){var d=E[a];E[a]=void 0===d||c?b:d;return E[a]},J=function(a,b,c,d){return(d||"http:"!=E.location.protocol?a:b)+c},xf=function(a){var b=K.getElementsByTagName("script")[0]||K.body||K.head;b.parentNode.insertBefore(a,b)},oa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},r=function(a,b,c){var d=K.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;oa(d,b);c&&(d.onerror=c);xf(d);return d},ca=function(a,b){var c=K.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";xf(c);oa(c,b);void 0!==a&&(c.src=a);return c},D=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},U=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},v=function(a){E.setTimeout(a,
0)},ra=!1,sa=[],Ef=function(a){if(!ra){var b=K.createEventObject,c="complete"==K.readyState,d="interactive"==K.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){ra=!0;for(var e=0;e<sa.length;e++)sa[e]()}sa.push=function(){for(var a=0;a<arguments.length;a++)v(arguments[a]);return 0}}},Ff=0,Gf=function(){if(!ra&&140>Ff){Ff++;try{K.documentElement.doScroll("left"),Ef()}catch(a){E.setTimeout(Gf,50)}}},If=function(a){var b=K.getElementById(a);if(b&&Hf(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(Hf(document.all[a][c],
"id")==a)return document.all[a][c];return b},Hf=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},Jf=function(a){return a.target||a.srcElement||{}},wa=function(a){var b=K.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},Kf=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&
(e=null);return e},Lf=!1,Mf=[],Nf=function(){if(!Lf){Lf=!0;for(var a=0;a<Mf.length;a++)Mf[a]()}},Of=function(a){a=a||E;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},ta=function(a){window.console&&window.console.log&&window.console.log(a)};var Pf=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||E.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||E.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:E.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=ef(d||[],k[k.length-
1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var m=f.split("&"),l=0;l<m.length;l++){var n=m[l].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Qf=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},xa=function(a){var b=K.createElement("a");
a&&(b.href=a);return b};var da=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ba=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=Pf(xa(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1},fa=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};var Rf=new jf,Sf={},Uf={set:function(a,b){Ia(Tf(a,b),Sf)},get:function(a){return L(a,2)},reset:function(){Rf=new jf;Sf={}}},L=function(a,b){if(2==b){for(var c=Sf,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Rf.get(a)},Tf=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Ba=function(a,b){U(a,"load",b,void 0)},aa=function(a,b,c){r(a,b,c)},C=E,Aa=function(a,b){C[a]=b},p=function(a,b,c){b&&(void 0===C[a]||c&&!C[a])&&(C[a]=b);return C[a]},t=function(a,b,c){return("https:"==E.location.protocol?a:b)+c};var Vf=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Wf={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Xf={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Yf=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Zf=function(){var a=L("gtm.whitelist");
var b=a&&Yf(gf(a),Wf),c=L("gtm.blacklist")||L("tagTypeBlacklist")||[];Vf.test(E.location&&E.location.hostname)&&(c=gf(c),c.push("nonGooglePixels","nonGoogleScripts"));var d=c&&Yf(gf(c),Xf),e={};return function(f){var g=f&&f[Hc];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>ef(b,g.a))if(g.b&&0<g.b.length)for(var k=0;k<g.b.length;k++){if(0>ef(b,
g.b[k])){h=!1;break a}}else{h=!1;break a}h=!0}var m=!1;if(c){var l;if(!(l=0<=ef(d,g.a)))a:{for(var n=g.b||[],q=new jf,u=0;u<d.length;u++)q.set(d[u],!0);for(u=0;u<n.length;u++)if(q.get(n[u])){l=!0;break a}l=!1}m=l}return e[g.a]=!h||m}};var uf=function(a){var b=K;return $f?b.querySelectorAll(a):null},ag=!1;if(K.querySelectorAll)try{var bg=K.querySelectorAll(":root");bg&&1==bg.length&&bg[0]==K.documentElement&&(ag=!0)}catch(a){}var $f=ag;var _eu=function(a){var b=String(L("gtm.elementUrl")||a[cc]||""),c=xa(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Ma};_e.a="e";_e.b=["google"];var gg=/(^|\.)doubleclick\.net$/i,hg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,ia=function(a){for(var b=String(K.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=ff(e[0]);if(f&&f==a){var g=ff(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},ig=function(a,b,c,d,e){if(gg.test(K.location.hostname)||"/"==c&&hg.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=K.cookie;K.cookie=f;return g!=
K.cookie||0<=ef(ia(a),b)},jg=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},kg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},lg=function(){var a=Pf(E.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var mg=function(a,b){this.f=a;this.j=b};mg.prototype.toString=function(){var a=""+this.f;1<this.j&&(a=a+"-"+this.j);return a};var ng=function(a,b){this.Da=a;this.ea=b};ng.prototype.toString=function(){return""+this.ea+"."+this.Da};var qg=function(a,b){var c=new og(null,a,b);pg(c);return c},og=function(a,b,c){this.La=Math.floor(I().getTime()/864E5);this.da=b||"auto";this.W=c||"/";var d=jg(this.da),e=kg(this.W);this.D=a||new mg(d,e);this.h=[];this.B=new jf},sg=function(a,b,c){b&&(""==c.Da?rg(a,b):(a.B.contains(b)||a.h.push(b),a.B.set(b,c)))},tg=function(a,b){for(var c=0;c<b.length;c++)sg(a,b[c][0],b[c][1])},rg=function(a,b){var c=ef(a.h,b);0<=c&&a.h.splice(c,1);a.B.set(b,void 0)},ug=function(a){for(var b=[],c=0;c<a.h.length;c++){var d=
a.h[c];b.push([d,a.B.get(d)])}return b},vg=function(a){for(var b=0,c=0;c<a.h.length;c++)b=Math.max(b,a.B.get(a.h[c]).ea);return 864E5*b};og.prototype.toString=function(){if(0==this.h.length)return"";for(var a=[],b=0;b<this.h.length;b++){var c=this.h[b];a.push(""+c+"."+this.B.get(c).toString())}return"GAX1."+this.D.toString()+"."+a.join("!")};
var wg=function(a,b){for(var c=new Date,d=kg(a.W),e=[],f=0;f<a.h.length;f++){var g=a.h[f];a.B.get(g).ea<a.La&&e.push(g)}for(f=0;f<e.length;f++)rg(a,e[f]);if(a.h.length>(b||10))return!1;c.setTime(vg(a));if("auto"!=a.da)return ig("_gaexp",a.toString(),a.W,a.da,c);for(var h=lg(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.D=new mg(jg(h[k]),d),ig("_gaexp",a.toString(),a.W,h[k],c)))return!0;return!1},pg=function(a){for(var b=a.D.f,c=a.D.j,d=ia("_gaexp"),e=[],f=0;f<d.length;f++){var g=xg(a,d[f]);g&&e.push(g)}tf(e,
function(a,d){var e=a.D,f=d.D;return e.f==f.f&&e.j==f.j?!1:e.f==b&&e.j==c?!0:f.f==b&&f.j==c?!1:e.f==b?f.f!=b||e.j<f.j:f.f==b?!1:e.j==c?f.f!=b&&(f.j!=c||e.f<f.f):f.j==c?!1:e.f<f.f||e.f==f.f&&e.j<f.j});a.D=0<e.length?e[0].D:new mg(b,c);for(f=e.length-1;0<=f;f--)tg(a,ug(e[f]))},xg=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=ff(e[0]);if(0!=f.length){var g=2==e.length?ff(e[1]):"1";d=df(f)&&df(g)?new mg(Q(f),Q(g)):void 0;
break a}}d=void 0}if(d){for(var h=new og(d,a.da,a.W),k=(c[2]||"").split("!"),m=0;m<k.length;m++){var l=k[m].split(".");if(3==l.length){if(!df(l[1]))return;sg(h,l[0],new ng(l[2],Q(l[1])))}}return h}}};var _f=function(a){var b=String(L("gtm.referrer")||K.referrer);if(!b)return b;var c=xa(b);return b};_f.a="f";_f.b=["google"];var ea=function(a){var b=E.location,c;(c=a[Sb]?a[Sb]:L("gtm.url"))&&(b=xa(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[Cb]&&(f=Pf(b,a[Cb],a[fe],a[bc],a[Td]));return f},_u=ea;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[ab])==String(a[bb])};_eq.a="eq";_eq.b=["google"];var Lg=Math.random(),Mg="1.000000">Lg;var Ng=af;var Og=af,Pg=[],Qg=!1,Rg=function(a){return E["dataLayer"].push(a)},Sg=function(a){var b=!1;return function(){!b&&P(a)&&v(nf(a));b=!0}},Yg=function(){for(var a=!1;!Qg&&0<Pg.length;){Qg=!0;var b=Pg.shift();if(P(b))try{b.call(Uf)}catch(va){}else if(bf(b))a:{var c=b;if("string"==Ga(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Sf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(va){}}}else{var k=b,m=void 0;for(m in k)if(k.hasOwnProperty(m)){var l=m,
n=k[m];Rf.set(l,n);Ia(Tf(l,n),Sf)}var q=!1,u=k.event,w=void 0;if(u){w=pf++;Ma=u;if(!k["gtm.uniqueEventId"]){var x=w;Rf.set("gtm.uniqueEventId",x);Ia(Tf("gtm.uniqueEventId",x),Sf)}var z=Sg(k.eventCallback),F=k.eventTimeout;F&&E.setTimeout(z,Number(F));q=Og(w,u,z,k.eventReporter)}La||(La=k["gtm.start"])&&Ng();var H=k,G=w,y=u,M=Sf;if(!q){var B=w,N=u;
}Ma=null;a=q||a}var T=b,R=Sf;Xg();Qg=!1}return!a},Zg=function(){var a=Yg();try{var b=E["dataLayer"].hide;if(b&&void 0!==b["GTM-WJLV88"]&&b.end){b["GTM-WJLV88"]=!1;var c=!0,d;for(d in b)if(!0===b[d]){c=!1;break}c&&(b.end(),
b.end=null)}}catch(e){}return a};var $g,ah,bh,ch=/(Firefox\D28\D)/g.test(wf.userAgent),ih=function(a,b){return function(c){c=c||E.event;var d=Jf(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=Kf(d,["a","area"]),e=!d||!d.href||dh(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?bh:ah;if(c.defaultPrevented||!1===c.returnValue||c.ra&&c.ra()){if(d){var g={simulateDefault:!1},h=eh(f,["wnc","nwnc"]);h&&fh(a,d,g,f.wt,h)}}else{if(d){var g={},k,m=eh(f,
["wnc","nwnc","nwc","wc"]);(k=fh(a,d,g,f.wt,m))||(gh(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&ch;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=hh(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},fh=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||Hf(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event=
"gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=jh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=kh(b);g.eventTimeout=f;g.eventCallback=lh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return Rg(g)},
kh=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},mh=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},hh=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(wf.userAgent),e=mh(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=E.frames&&E.frames[f]||E[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+I().getTime(),b.targetWindow=E.open("",b.targetWindowName));break;default:d&&!E.frames[e]?(b.simulateDefault=!1,c=!0):(E.frames[e]||(b.targetWindowName=e),b.targetWindow=E.frames[e]||E.open("",e))}return c},jh=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||I().getTime(),500>I().getTime()-c&&E.setTimeout(jh(a,b,c),25)))}},lh=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);K.gtmSubmitFormNow=!0;nh(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||I().getTime(),500>I().getTime()-c&&E.setTimeout(lh(a,b,c),25)}},eh=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},oh=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},gh=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<ph.length;c++)if(a.passingRules[c]){var d=qh[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=ph[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},rh=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(K.gtmHasClickListenerTag)return;K.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=Jf(a);b&&fh("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!$g&&($g=Qf(K.location));oh(ah,b||!1,c||!1,d,e);if(K.gtmHasLinkClickListenerTag)return;
K.gtmHasLinkClickListenerTag=!0;f="click";g=ih(a,b||!1);break;case "FORM_SUBMIT":oh(bh,b||!1,c||!1,d,e);if(K.gtmHasFormSubmitListenerTag)return;K.gtmHasFormSubmitListenerTag=!0;f="submit";g=ih(a,b||!1);break;default:return}U(K,f,g,h)},dh=function(a){if(!$g)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=xa(a);return $g==Qf(c)},nh=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
K.gtmFormElementSubmitter||(K.gtmFormElementSubmitter=K.createElement("form"));return K.gtmFormElementSubmitter.submit.call?K.gtmFormElementSubmitter.submit:a.submit};var yg=new String("undefined"),zh=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===yg?b:a[d]);return c.join("")}};zh.prototype.toString=function(){return this.resolve("undefined")};zh.prototype.valueOf=zh.prototype.toString;var Ah={},Bh=function(a,b){var c=pf++;Ah[c]=[a,b];return c},Ch=function(a){var b=a?0:1;return function(a){var c=Ah[a];if(c&&P(c[b]))c[b]();Ah[a]=void 0}};var Dh=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Eh=function(a,b){return a<b?-1:a>b?1:0};var Fh;a:{var Gh=Ca.navigator;if(Gh){var Hh=Gh.userAgent;if(Hh){Fh=Hh;break a}}Fh=""}var V=function(a){return-1!=Fh.indexOf(a)};var Ih=function(a){Ih[" "](a);return a};Ih[" "]=function(){};var Kh=function(a,b){var c=Jh;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Lh=V("Opera"),Mh=V("Trident")||V("MSIE"),Nh=V("Edge"),Oh;if(Oh=V("Gecko"))Oh=!(-1!=Fh.toLowerCase().indexOf("webkit")&&!V("Edge"));var Ph=Oh&&!(V("Trident")||V("MSIE"))&&!V("Edge"),Qh=-1!=Fh.toLowerCase().indexOf("webkit")&&!V("Edge");Qh&&V("Mobile");V("Macintosh");V("Windows");V("Linux")||V("CrOS");var Rh=Ca.navigator||null;Rh&&(Rh.appVersion||"").indexOf("X11");V("Android");!V("iPhone")||V("iPod")||V("iPad");V("iPad");V("iPod");
var Sh=function(){var a=Ca.document;return a?a.documentMode:void 0},Th;a:{var Uh="",Vh=function(){var a=Fh;if(Ph)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Nh)return/Edge\/([\d\.]+)/.exec(a);if(Mh)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Qh)return/WebKit\/(\S+)/.exec(a);if(Lh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Vh&&(Uh=Vh?Vh[1]:"");if(Mh){var Wh=Sh();if(null!=Wh&&Wh>parseFloat(Uh)){Th=String(Wh);break a}}Th=Uh}
var Xh=Th,Jh={},Yh=function(a){return Kh(a,function(){for(var b=0,c=Dh(String(Xh)).split("."),d=Dh(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],m=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==m[0].length)break;b=Eh(0==k[1].length?0:parseInt(k[1],10),0==m[1].length?0:parseInt(m[1],10))||Eh(0==k[2].length,0==m[2].length)||Eh(k[2],m[2]);g=k[3];h=m[3]}while(0==b)}return 0<=b})},Zh=Ca.document,
$h=Zh&&Mh?Sh()||("CSS1Compat"==Zh.compatMode?parseInt(Xh,10):5):void 0;var ai;if(!(ai=!Ph&&!Mh)){var bi;if(bi=Mh)bi=9<=Number($h);ai=bi}ai||Ph&&Yh("1.9.1");Mh&&Yh("9");var ua=function(a,b){var c="";Mh&&!ci(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(di)a.srcdoc=d;else if(ei){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else fi(a,d)},di=Qh&&"srcdoc"in document.createElement("iframe"),ei=Ph||Qh||Mh&&Yh(11),fi=function(a,b){Mh&&Yh(7)&&!Yh(10)&&6>gi()&&hi(b)&&(b=ii(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};Mh&&!ci(a)?ji(a,c):c()},gi=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},ci=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{Ih(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},ki=0,ji=function(a,b){var c="goog_rendering_callback"+ki++;window[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},hi=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},ii=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var mi=function(a,b,c,d){return function(){try{if(0<b.length){var e=b.shift(),f=mi(a,b,c,d);if("SCRIPT"==String(e.nodeName).toUpperCase()&&"text/gtmscript"==e.type){var g=K.createElement("script");g.async=!1;g.type="text/javascript";g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";e.charset&&(g.charset=e.charset);var h=e.getAttribute("data-gtmsrc");h&&(g.src=h,oa(g,f));a.insertBefore(g,null);h||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(var k=[];e.firstChild;)k.push(e.removeChild(e.firstChild));
a.insertBefore(e,null);mi(e,k,f,d)()}else a.insertBefore(e,null),f()}else c()}catch(m){v(d)}}};var oi=function(a,b,c){if(K.body){var d=
a[Nc];d instanceof zh&&(d=d.resolve(Bh(b,c)),b=af);if(a[Qe])try{ua(ca(),"<script>var google_tag_manager=parent.google_tag_manager;\x3c/script>"+d),v(b)}catch(e){v(c)}else a[Se]?ni(d,b,c):mi(K.body,wa(d),b,c)()}else E.setTimeout(function(){oi(a,b,c)},200)},_html=oi;_html.a="html";_html.b=["customScripts"];
var Ai=function(a,b,c,d){var e=b+": "+c+(d?" !important":""),f=document;if(f.createStyleSheet){var g=xi(f),h=g.rules.length;g.addRule(a,e);return function(){g.removeRule?g.removeRule(h):g.deleteRule(h);g.addRule("x","-",h)}}var k=yi(a+"{"+e+"}",f);zi(k,f);var m=k.parentNode;return function(){m.removeChild(k)}},Bi=null,xi=function(a){if(Bi)return Bi;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return Bi=c}0==a.styleSheets.length&&
a.createStyleSheet();return Bi=a.styleSheets[0]},yi=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},zi=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var Ii={},Ji=void 0,Ki=function(a){var b=Ii[a];b||(b={id:a,u:[],T:0,Ga:null,xa:void 0,Ba:!1},Ii[a]=b);Ji=b},Mi=function(a,b,c,d){var e=Ji;if(!$f||!e)return!1;var f={id:e.id+":"+e.u.length,bb:b,R:[],Xa:c,F:a,pa:0,na:d||null,Ka:0,S:!1};e.u.push(f);null===a?(f.S=!0,b(null)):Li(e);return!0},Ni=function(a){var b=Ai(a,"visibility","hidden",!0);return function(){P(b)&&b.apply();b=null}},Oi=function(a,b,c,d){var e=b;if(!ra){var f=Ni(a.w);sa.push(f);e=function(a,c){var d=b(a,c);f();return d}}return Mi(a,e,
c,d)},Li=function(a){if(!a.Ba){for(var b=a.T;b<a.u.length;b++){var c=a.u[b],d=b==a.T;if(!c.S&&!Pi(d,c))break;c.S&&d&&a.T++}a.u.length>a.T?(a.Ga||(a.Ga=E.setTimeout(function(){a.Ga=null;Li(a)},80)),ra||a.xa||(a.xa=function(){v(function(){Li(a)})},U(K,"DOMContentLoaded",a.xa))):Qi(a)}},Qi=function(a){for(var b=0;b<a.u.length;b++){var c=a.u[b];if(c.F)for(var d=uf(c.F.w)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Ri(f,c.id),c.R.push(Si(f,c.id)))}}},Pi=
function(a,b){var c=[];if(b.F){var d=Ti(b.F,b.id),e=null;b.na&&(e=Ti(b.na,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!ra&&(null===b.na.o||b.Ka+c.length<b.na.o)))break;c.push({element:g,Hb:h})}}if(!ra&&b.Xa&&(!a||null==b.F.o||b.F.o!=b.pa+c.length))return!1;for(var k=0;k<c.length;k++){var m=c[k].element,l=c[k].Hb,n;b.pa++;Ri(m,b.id);l&&(b.Ka++,n=b.id+"-t",Ri(l,n));var q=b.bb(m,l);P(q)&&b.R.push(q);b.R.push(Si(m,b.id));l&&n&&b.R.push(Si(l,n))}if(b.F.o&&
b.F.o==b.pa||ra)b.S=!0;return!0},Ri=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Si=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Ti=function(a,b){for(var c=uf(a.w)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.C&&!Ui(f))break;d.push(f)}}return d},Ui=function(a){if(ra)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Xi,Yi;var hj=function(a){return function(){}},ij=function(a){return function(){}};var Lj=function(a){var b=E||Ca,c=b.onerror,d=!1;Qh&&!Yh("535.3")&&(d=!d);b.onerror=function(b,f,g,h,k){c&&c(b,f,g,h,k);a({message:b,fileName:f,zb:g,Yb:h,error:k});return d}};var hk=30,ik=[],jk=[],kk=[],lk=new jf,mk=[],Y=[],ph=[],qh=[],nk=function(){this.I=[]};nk.prototype.set=function(a,b){this.I.push([a,b]);return this};nk.prototype.resolve=function(a,b){for(var c={},d=0;d<this.I.length;d++){var e=ok(this.I[d][0],a,b),f=ok(this.I[d][1],a,b);c[e]=f}return c};var pk=function(a){this.index=a};pk.prototype.resolve=function(a,b){var c=kk[this.index];if(c&&!b(c)){var d=c[Sc];if(a){if(a.get(d))return;a.set(d,!0)}c=ok(c,a,b);a&&a.set(d,!1);return kf(c)}};
var _M=function(a){return new pk(a)},qk=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=ok(ik[a[f]],b,c);g===yg&&(e=!0);d.push(g)}return e?new zh(d):d.join("")}},_T=function(a){return new qk(arguments)},rk=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=ok(a[0],c,d);if(a[0]instanceof pk&&b(8)&&b(16)){if(e===yg)return e;var f=ka();lk.set(f,e);return'google_tag_manager["GTM-WJLV88"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=W[a[g]](e);return e}},_E=function(a,b){return new rk(arguments)},sk=function(a,b){this.v=a;this.ma=b},_R=function(a,b){return new sk(a,b)},ok=function(a,b,c){var d=a;if(a instanceof pk||a instanceof nk||a instanceof qk||a instanceof rk)return a.resolve(b,c);if(!(a instanceof sk))if(bf(a))for(var d=
[],e=0;e<a.length;e++)d[e]=ok(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=ok(a[f],b,c))}return d},tk=function(a,b){var c=b[a],d=c;if(c instanceof pk||c instanceof rk||c instanceof qk||c instanceof sk)d=c;else if(bf(c))for(var d=[],e=0;e<c.length;e++)d[e]=tk(c[e],b);else if("object"==typeof c){var d=new nk,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],tk(c[f],b))}return d},vk=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");
0==a&&(e[1]=ik[e[1]]);if(1==a)for(var f=uk(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=jk[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=uk(e[g]);3==a&&(c[d]=ik[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=ik[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},uk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<hk;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:
62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},wk=function(a,b,c){a.push.apply(a,vk(b,c))};
var Ug=function(){},Ek=function(a){},Xg=function(){},Fk=function(a){},Gk=function(a,b){},Hk=function(a,b){},Vg=function(a){};var Ik=function(a){var b=this;this.g=a;this.complete=this.Ta=!1;this.la=[];this.fa=[];this.O=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||of(b.la);sf(b,1);if(Oa[a])for(var e=0;e<Oa[a].length;e++)Oa[a].shift().O()};this.N=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||
of(b.fa);sf(b,2);if(Oa[a])for(var e=0;e<Oa[a].length;e++)Oa[a].shift().N()};this.A=af},Jk=function(a,b){a.la.push(b)},Kk=function(a,b){a.fa.push(b)},Lk=function(a){this.J=[];this.Ea=[];this.Ma={};this.va=[];this.U=0;this.Ra={};this.Ua={};this.Fa={};this.event=a};Lk.prototype.addListener=function(a){this.va.push(a)};
var Mk=function(a,b,c,d,e,f){if(!c.complete){a.J[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=bf(d)?d.slice():["or",d];e=bf(e)?e.slice():[e];f=bf(f)?f.slice():[f];a.Ma[b]=d;a.Ra[b]=0<e.length;a.Ua[b]=0<f.length;a.U++;var g=function(){0<a.U&&a.U--;0<a.U||of(a.va)};Jk(c,g);Kk(c,g)}},Nk=function(a,b,c){a.J[b]&&(Jk(a.J[b],function(){c(b,!0)}),Kk(a.J[b],function(){c(b,!1)}))},Ok=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof sk&&a[g].v===
d||a[g]===d){f=g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},Sk=function(a,b){var c=[],d=!1,e=function(b){var f,g,h=Y[b];if(a.event.c(h)){}else g=Pk(h,b,a);if(f=g){var k=Qk(b,!0);0<k.length&&e(k[0].v);c.push(f);var l=Qk(b,!1);0<l.length&&e(l[0].v)}else d=
!0};e(b);if(!d){for(var f=0;f<c.length;f++){var g=c[f],h=Qk(g.g,!0);if(0<h.length){var k=c[f-1],m=Rk(g);Jk(k,m);0==h[0].ma&&Kk(k,m)}var l=Qk(g.g,!1);0<l.length&&(m=Rk(c[f+1]),Jk(g,m),0==l[0].ma&&Kk(g,m))}a.Ea.push(c)}},Qk=function(a,b){var c=b?ce:te,d=Y[a],e=void 0===d[c]?[]:d[c];return bf(e)?e:[e]},Rk=function(a){return function(){a.A()}},Uk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Qk(a,!0);0<b.length&&f(b[0].v);e.push(a);var c=Qk(a,!1);0<c.length&&f(c[0].v)};
f(d.g);b[d.g]=e}Tk(a,b);return b},Tk=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<ef(b[e],d)){delete b[d];break}}};var Wk=function(a,b){return function(){a[Jc]=b.O;a[Kc]=b.N;var c=b.g,d=b.s&&b.s.Fa[c],e=Na[c]&&Na[c].state,f=d?void 0!==d:b.Ta||b.Zb,g=Na[c]&&Na[c].firingOption,h=g&&2==g,k=g&&1==g;if(!f&&void 0===e||!f&&!h||!h&&!k){sf(b,0);var m=b.s?b.s.event:void 0;a=Vk(a,m?m.c:Zf());if(m){var l=a;Gk(m,c)}kf(a,b.O,b.N)}else h&&0==e||k&&0==d?Oa[c].push(b):h&&1==e||k&&1==d?b.O():b.N()}},Vk=function(a,b){a=ok(a,new jf,b);return a},Pk=function(a,b,c){var d=new Ik(b);d.s=c;Jk(d,hj(a));Kk(d,ij(a));d.A=Wk(a,d);return d};
var $k=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];E[m()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){var b=function(a,b,c){if(!la(b))return!1;for(var e=ma(Object(b),c,[]),f=0;e&&f<e.length;f++)d(a,e[f]);return!!e&&0<e.length},c;a[kc]?c=L("ecommerce"):
a[jc]&&(c=a[jc].ecommerce);if(!la(c))return;c=Object(c);var e=ma(a[Ec],"currencyCode",c.currencyCode);void 0!==e&&d("set","&cu",e);b("ec:addImpression",c,"impressions");if(b("ec:addPromo",c[c.promoClick?"promoClick":"promoView"],"promotions")&&c.promoClick){d("ec:setAction","promo_click",c.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=c[f[g]];if(h){b("ec:addProduct",h,"products");d("ec:setAction",f[g],
h.actionField);break}}}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&w[e]||!c&&void 0===w[e])){var f=x[e]?ha(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}O("GoogleAnalyticsObject",a[nd]||"ga",!1);var m=function(){return E.GoogleAnalyticsObject},l=O(m(),function(){var a=E[m()];a.q=a.q||[];a.q.push(arguments)},!1);l.l=Number(I());var n="",q="";"string"!=typeof a[Ge]?(q=ka(),n=q+"."):""!==
a[Ge]&&(q=a[Ge],n=q+".");var u=!1;
var z={name:q};l("create",a[Qa],z);d("set","&gtm","GTM-WJLV88");var H;a[cd]&&d("require","linkid","linkid.js");d("set","hitCallback",function(){if(P(a[Lc]))a[Lc]();else{var c=a[Ec],d=c&&c.hitCallback;P(d)&&d()}b()});if(a[Ce]){}else if(a[De]){}else if(a[Fe]){}else if(a[Ee]){}else if(a[ac]){}else if(a[Zb]){}else if(a[Be]){}else{a[sc]&&(d("require","ec","ec.js"),h());if(a[ic]&&!a[uc]){var R="_dc_gtm_"+String(a[Qa]).replace(/[^A-Za-z0-9-]/g,"");d("require","displayfeatures",void 0,{cookieName:R})}H?d("send","pageview",H):d("send","pageview");}if(!$k){var X=a[Xb]?"u/analytics_debug.js":"analytics.js";a[Tc]&&!a[Xb]&&(X="internal/"+X);
$k=!0;r(J("https:","http:","//www.google-analytics.com/"+X,u),function(){E[m()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var al,bl;var kl=!1;var ll=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=mk[b]&&ok(mk[b],new jf,c),e=d;if(d)if(d[$a]&&bf(d[bb]))for(var f=d[bb],e=!1,g=0;!e&&g<f.length;g++)d[bb]=f[g],e=kf(d);else e=kf(d);a[b]=[e,d]}return a[b]}},Dk=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.M(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.M(e[d],a.c)[0])return!1;return!0},ml=!1,Og=function(a,b,c,d){switch(b){case "gtm.js":if(ml)return!1;ml=!0;break;case "gtm.sync":if(L("gtm.snippet")!=Ka)return!1}L("tagTypeBlacklist");
for(var e={id:a,name:b,ba:c||af,aa:uk(),ka:uk(),M:ll(),c:Zf()},f=[],g=0;g<ph.length;g++)if(Dk(e,ph[g])){f[g]=!0;for(var h=e,k=ph[g],m=k[1],l=0;l<m.length;l++)h.aa[m[l]]=!0;for(var n=k[3],l=0;l<n.length;l++)h.ka[n[l]]=!0}else f[g]=!1;Gk(e);var u=[];for(var w=0;w<hk;w++)if(e.aa[w]&&!e.ka[w])if(e.c(Y[w])){}else{u[w]=Y[w];}e.P=u;for(var x=new Lk(e),z=0;z<hk;z++)if(e.aa[z]&&!e.ka[z])if(e.c(Y[z])){}else{var F=e.P[z],H=Pk(F,z,x);Mk(x,z,H,F[dc],F[ce],F[te]);if(F[Pa])break}x.addListener(e.ba);for(var G=[],
y=0;y<x.J.length;y++){var M=x.J[y];if(M){var A=x.Ma[y],B=x.Ra[y],N=x.Ua[y];if(0!=A.length||B||N){if(0<A.length)for(var T=Ok(A,M.A),R=0;R<A.length;R++)A[R]instanceof sk&&A[R].v!=y&&Nk(x,A[R].v,T);(B||N)&&Sk(x,y)}else G.push(y)}}for(y=0;y<G.length;y++)x.J[G[y]].A();for(y=0;y<x.Ea.length;y++){for(var va=x.Ea[y],X=va,ja=[],ga=0;ga<X.length;ga++){var qb=X[ga],ob=qb.g,Nb=Na[ob],rd=Nb.firingOption;0!=rd&&(1==rd&&void 0!==qb.s.Fa[ob]||2==rd&&void 0!==Nb.state)&&ja.push(qb)}var sd=Uk(ja),wc=void 0;for(wc in sd)if(sd.hasOwnProperty(wc)){for(var yf=
void 0,nj=void 0,od=sd[wc],zl=od[0],uj=od[od.length-1],vj,Ja=0;Ja<X.length;Ja++){var pd=X[Ja];!yf&&pd.g==zl&&0<Ja&&(yf=X[Ja-1]);pd.g==uj&&Ja<X.length-1&&(nj=X[Ja+1]);if(-1<ef(od,pd.g))if(vj=X.splice(Ja,1)[0],pd.g==uj)break;else Ja--}if(vj){var wj=Number(wc),na=yf,zf=nj;if(na){var Al=na.la[0],Bl=na.fa[0],xj=na;xj.la=[];xj.fa=[];Jk(na,Al);Kk(na,Bl)}if(na&&zf){var Af=Rk(zf);Jk(na,Af);var Bf=Qk(na.g,!1);0<Bf.length&&Bf[0].v!=wj&&0==Bf[0].ma&&Kk(na,Af);var Cf=Qk(zf.g,!0);0<Cf.length&&Cf[0].v!=wj&&0==Cf[0].ma&&
Kk(na,Af)}}}0<va.length&&va[0].A()}0<x.U||of(x.va);d&&P(d)&&d({passingRules:f,resolvedTags:e.P});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var Aj in e.P)if(e.P.hasOwnProperty(Aj)){var Bj=e.P[Aj],Df;if(!(Df=void 0==Bj[Sc])){var Cj=Bj[Sc];Df=!("function"!=typeof String.prototype.startsWith?0===Cj.indexOf("_implicit"):Cj.startsWith("_implicit"))}if(Df)return!0}return!1};var nl={macro:function(a){if(lk.contains(a))return lk.get(a)}};nl.dataLayer=Uf;nl.onHtmlSuccess=Ch(!0);nl.onHtmlFailure=Ch(!1);nl.callback=function(a){za.hasOwnProperty(a)&&P(za[a])&&za[a]();delete za[a]};nl.hb=function(){var a=E.google_tag_manager;a||(a=E.google_tag_manager={});a["GTM-WJLV88"]||(a["GTM-WJLV88"]=nl);pa=a};(function(){var a=function(a){var b=O("google_tag_manager",{},!1),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};ah=a("linkClickMap");bh=a("formSubmitMap")})();
ik.push.apply(ik,function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','1568237_2147479553',_ua,true,'UA-44655428-2',false,'\x26tid',{10:8},2,_html,'\x3cscript type\x3d\x22text/gtmscript\x22\x3e(function(b,a,c,d,e,f){b.CoscaleObj\x3d{e:0,t:e,b:f};b\x3da.createElement(c);a\x3da.getElementsByTagName(c)[0];b.src\x3dd;a.parentNode.insertBefore(b,a)})(window,document,\x22script\x22,\x22//rum-mon.coscale.com/rum/v1/js/coscale-rum.js\x22,\x2200020f49-e8af-4816-bf71-d824efe83061\x22,\x22//rum-mon.coscale.com\x22);\x3c/script\x3e',1,_u,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],c=0;c<a.length;c++)b[c]=tk(c,a);return b}());wk(jk,0,"10:0,10:1,12:2,2:3,3:4,10:6,14:7,0:8,9:9,8:9,17:9,5:9,6:9,1:11,13:9,7:9,16:12,10:13,15:7,11:14,16:15,10:16,12:17,12:18,4:19,12:20,4:21,10:22,12:23,12:24");wk(kk,1,"G,AAAY,AAAoB,AAAIG,AAAAY,CAAAg");wk(mk,1,"Z");wk(Y,1,"g_f,AAgH");wk(ph,2,"B:D::");wk(qh,4,"5.5:");for(var ol=0;ol<Y.length;ol++){var pl=Y[ol],ql=1;pl[yd]?ql=2:pl[Me]&&(ql=0);Na[ol]={firingOption:ql,state:void 0};Oa[ol]=[]}nl.hb();
(function(a){})("async");
(function(){var a=O("dataLayer",[],!1),b=O("google_tag_manager",{},!1),b=b["dataLayer"]=b["dataLayer"]||{};sa.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Mf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Pg.push.apply(Pg,b);300<this.length;)this.shift();return Yg()};Pg.push.apply(Pg,a.slice(0));v(Zg)})();
if("interactive"==K.readyState&&!K.createEventObject||"complete"==K.readyState)Ef();else{U(K,"DOMContentLoaded",Ef);U(K,"readystatechange",Ef);if(K.createEventObject&&K.documentElement.doScroll){var yl=!0;try{yl=!E.frameElement}catch(a){}yl&&Gf()}U(E,"load",Ef)}"complete"===K.readyState?Nf():U(E,"load",Nf);
(function(a){})("async");(function(){})();var _vs="res_ts:1445349291859000,srv_cl:132752946,ds:live,cv:3";
})()
